language: node_js
cache:
  directories:
  - $HOME/build/unfoldingWord-dev/ts-desktop/node_modules
sudo: false
node_js:
- '5.1'
before_script:
- npm install
- npm install gulp -g
script: gulp
before_install:
    - openssl aes-256-cbc -K $encrypted_bf9158fc3bc8_key -iv $encrypted_bf9158fc3bc8_iv -in config-test.json.enc -out config-test.json -d
#- openssl aes-256-cbc -K $encrypted_09d7304f2fad_key -iv $encrypted_09d7304f2fad_iv
#    -in config.json.enc -out unit_tests/git/config.json -d
